require 'net/smtp'

module Yolo
  module Notify
    module Ios
      #
      # OTAEmail generates an HTML email for OTA build notifications
      #
      # @author [Alex Fish]
      #
      class OTAEmail < Yolo::Notify::Email

        #
        # The OTA Email body content, this content is generated using release_notes.md
        # and an HTML email template in the same directory (email.html)
        # @param  opts [Hash] The options hash from super
        #
        def body(opts)
          message = <<MESSAGE_END
To: A Test User <test@todomain.com>
MIME-Version: 1.0
Content-type: text/html
Subject: #{opts[:subject]}

#{parsed_body(opts)}
MESSAGE_END
        end

        #
        # Returns HTML ready to be used in the email body, HTML is generated by
        # parsing the email.html template and applying realease_notes.md content
        # @param  opts [Hash] The options hash from super
        #
        # @return [String] HTML body content for emailing
        def parsed_body(opts)
          file = File.open(File.dirname(__FILE__) + "/email.html", "r")
          content = file.read
          markdown = Yolo::Tools::Ios::ReleaseNotes.html

          content = content.gsub("YOLO.TITLE",opts[:title])
          content = content.gsub("YOLO.CONTENT",markdown)
          content = content.gsub("YOLO.PASSWORD","<h3>Password</h3><hr><p>#{opts[:ota_password]}</p>")
          content = content.gsub("YOLO.LINK",opts[:ota_url])
          content
        end

      end
    end
  end
end
